---
apiVersion: v1
kind: ConfigMap
metadata:
 name: cart-config
data:
 REDIS_HOST: "redis"
 CATALOGUE_HOST: "http://catalogue"

---
apiVersion: v1
kind: Pod
metadata:
 name: cart
 labels:
  server: cart
  tier: app
spec:
 containers:
  - name: cart
    imagePullPolicy: Always
    image: gopalareddy/cart:k8
    envFrom:
    - configMapRef:
        name: cart-config
    resources:
     requests:
      cpu: "100m"
      memory: "128Mi"
     limits:
      cpu: "100m"
      memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
 name: cart
spec:
 selector:
  server: cart
  tier: app
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
 