---
apiVersion: v1
kind: Pod
metadata:
 name: mongodb
 labels:
  server: mongodb
  tier: db
spec:
 containers:
  - name: mongodb
    imagePullPolicy: Always
    image: gopalareddy/mongodb:k8
    ports:
     - containerPort: 27017
    # resources:
    #  requests:
    #   cpu: "100m"
    #   memory: "128Mi"
    #  limits:
    #   cpu: "100m"
    #   memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
 name: mongodb
spec:
 selector:
  server: mongodb
  tier: db
 ports:
  - protocol: TCP
    port: 80
    targetPort: 27017
 