---
apiVersion: v1
kind: ConfigMap
metadata:
 name: catalogue-config
data:
 MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: v1
kind: Pod
metadata:
 name: catalogue
 labels:
  server: catalogue
  tier: app
spec:
 containers:
  - name: catalogue
    imagePullPolicy: Always
    image: gopalareddy/catalogue:k8
    envFrom:
    - configMapRef:
        name: catalogue-config
    resources:
     requests:
      cpu: "100m"
      memory: "128Mi"
     limits:
      cpu: "100m"
      memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
 name: catalogue-service
spec:
 selector:
  server: catalogue
  tier: app
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
 